### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by JagaRamesh** [deepjhavar/intro-data-capstone-biodiversity#2]
Overall good job with the analysis! 

There are opportunities for improvement in powerpoint documentation.
I noticed few spelling errors, so would recommend to check for spelling before submission.
The Matplotlib graphs in part1 is neat with proper title, xlabel and ylabel.
I would suggest to include "Recommendation to conservationists" / conclusion for Part-I immediately after Part-I instead of in the last slide.

I would like to highlight some guidelines for powerpoint slides to make it more appealing :
1. Lighter background(instead of Black).
2. Use larger font size and try capturing the outcome of analysis in bullet points rather in paragraphs.
3. You can also use one part of the slide for charts/plots and use the other side to capture the findings.

In Part2 Slide, the xaxis labels are overlapping and the park names are not readable in the plot.
The conclusion is missing for Part2 and the following questions are unanswered:
How many weeks would you need to observe sheep at Bryce National Park in order to observe enough sheep? 
How many weeks would you need to observe at Yellowstone National Park to observe enough sheep?

Good analysis! Make sure the conclusion addresses the questions asked.

**Comment by deepjhavar** [comment]
thank you , There is one doubt i had , so the exercise on code academy , i can give the answer for yellow stone national park that it would take one week to observe but with  bryce i am confused , There were only 250 observations so i would assume half a week but on code academy when i do 510/250 it gives the correct answer. So i wanted to ask you what is the correct conclusion.
